import subprocess
import sys
from pathlib import Path


def run_cli(cwd: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "ml_autoresearch.cli", *args],
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def write_project(root: Path, data_mounts: str = "") -> None:
    (root / "CONTEXT.md").write_text("context v1\n")
    (root / "EXPERIMENT_INDEX.md").write_text("index v1\n")
    (root / "research-ledger.jsonl").write_text('{"event_type":"proposal_created"}\n')
    (root / "docs").mkdir()
    (root / "docs" / "guide.md").write_text("docs\n")
    (root / "agent-boundary.toml").write_text(
        """
[agent_control_boundary]
distro = "debian"
image = "../../containers/ml-autoresearch-agent"
allow_egress = true
""".lstrip()
        + data_mounts
    )


def test_prepare_agent_boundary_generates_layout_and_preserves_workspace_outputs(tmp_path: Path):
    write_project(tmp_path)
    preserved = tmp_path / "agent-work" / "scratch" / "keep.txt"
    preserved.parent.mkdir(parents=True)
    preserved.write_text("do not delete\n")
    settings = tmp_path / "agent-work" / ".pi" / "settings.json"
    settings.parent.mkdir(parents=True)
    settings.write_text("{}\n")

    completed = run_cli(tmp_path, "prepare-agent-boundary")

    assert completed.returncode == 0, completed.stderr
    assert (tmp_path / "agent-reference" / "CONTEXT.md").read_text() == "context v1\n"
    assert (tmp_path / "agent-reference" / "EXPERIMENT_INDEX.md").read_text() == "index v1\n"
    assert (tmp_path / "agent-history" / "research-ledger.jsonl").read_text() == '{"event_type":"proposal_created"}\n'
    for relative in ["candidates", "runs", "research-notes"]:
        assert (tmp_path / "agent-history" / relative).is_dir()
    for relative in [
        "drafts/candidates",
        "submissions",
        "research-notes",
        "capability-requests",
        "evaluation-requests",
        "campaign-reports",
        "scratch",
    ]:
        assert (tmp_path / "agent-work" / relative).is_dir()
    assert preserved.read_text() == "do not delete\n"
    assert settings.read_text() == "{}\n"


def test_prepare_agent_boundary_generates_managed_fort_config_with_data_mounts(tmp_path: Path):
    data_root = tmp_path / "gvccs-data"
    data_root.mkdir()
    write_project(
        tmp_path,
        f'''
[[data_mounts]]
name = "gvccs"
path = "{data_root}"
''',
    )
    old_dropin = tmp_path / "agent-work" / ".pi" / "fort.d" / "old.toml"
    old_dropin.parent.mkdir(parents=True)
    old_dropin.write_text("old\n")

    completed = run_cli(tmp_path, "prepare-agent-boundary")

    assert completed.returncode == 0, completed.stderr
    fort_toml = (tmp_path / "agent-work" / ".pi" / "fort.toml").read_text()
    assert "# Generated by ml-autoresearch prepare-agent-boundary" in fort_toml
    for target in [
        'target="/reference"',
        'target="/history"',
        'target="/history/candidates"',
        'target="/history/runs"',
        'target="/history/research-notes"',
        'target="/docs"',
        'target="/data/gvccs"',
    ]:
        assert target in fort_toml
    assert f'path="{data_root}"' in fort_toml
    assert 'target="/data/gvccs", readonly=true' in fort_toml
    assert not old_dropin.exists()
    assert (tmp_path / "agent-work" / ".pi" / "fort.d" / "README.md").is_file()


def test_prepare_agent_boundary_fails_for_missing_data_mount_path(tmp_path: Path):
    write_project(
        tmp_path,
        '''
[[data_mounts]]
name = "missing"
path = "missing-data"
''',
    )

    completed = run_cli(tmp_path, "prepare-agent-boundary")

    assert completed.returncode == 1
    assert "data mount path does not exist" in completed.stderr


def test_prepare_agent_boundary_rejects_invalid_and_overlapping_data_targets(tmp_path: Path):
    data_root = tmp_path / "data"
    data_root.mkdir()
    write_project(
        tmp_path,
        f'''
[[data_mounts]]
name = "one"
path = "{data_root}"
target = "/data/nested/one"

[[data_mounts]]
name = "two"
path = "{data_root}"
target = "/data/one"
''',
    )

    completed = run_cli(tmp_path, "prepare-agent-boundary")

    assert completed.returncode == 1
    assert "direct children of /data" in completed.stderr

    (tmp_path / "agent-boundary.toml").write_text(
        f'''
[agent_control_boundary]
distro = "debian"
image = "../../containers/ml-autoresearch-agent"
allow_egress = true

[[data_mounts]]
name = "one"
path = "{data_root}"
target = "/data/shared"

[[data_mounts]]
name = "two"
path = "{data_root}"
target = "/data/shared"
'''.lstrip()
    )
    completed = run_cli(tmp_path, "prepare-agent-boundary")

    assert completed.returncode == 1
    assert "overlapping data mount target" in completed.stderr
